/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package connectDB;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-03-10")
public class plane implements org.apache.thrift.TBase<plane, plane._Fields>, java.io.Serializable, Cloneable, Comparable<plane> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("plane");

  private static final org.apache.thrift.protocol.TField ID_PLANE_FIELD_DESC = new org.apache.thrift.protocol.TField("id_plane", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PLANENAME_FIELD_DESC = new org.apache.thrift.protocol.TField("planename", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new planeStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new planeTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String id_plane; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String planename; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID_PLANE((short)1, "id_plane"),
    PLANENAME((short)2, "planename");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID_PLANE
          return ID_PLANE;
        case 2: // PLANENAME
          return PLANENAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID_PLANE, new org.apache.thrift.meta_data.FieldMetaData("id_plane", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PLANENAME, new org.apache.thrift.meta_data.FieldMetaData("planename", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(plane.class, metaDataMap);
  }

  public plane() {
  }

  public plane(
    java.lang.String id_plane,
    java.lang.String planename)
  {
    this();
    this.id_plane = id_plane;
    this.planename = planename;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public plane(plane other) {
    if (other.isSetId_plane()) {
      this.id_plane = other.id_plane;
    }
    if (other.isSetPlanename()) {
      this.planename = other.planename;
    }
  }

  public plane deepCopy() {
    return new plane(this);
  }

  @Override
  public void clear() {
    this.id_plane = null;
    this.planename = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getId_plane() {
    return this.id_plane;
  }

  public plane setId_plane(@org.apache.thrift.annotation.Nullable java.lang.String id_plane) {
    this.id_plane = id_plane;
    return this;
  }

  public void unsetId_plane() {
    this.id_plane = null;
  }

  /** Returns true if field id_plane is set (has been assigned a value) and false otherwise */
  public boolean isSetId_plane() {
    return this.id_plane != null;
  }

  public void setId_planeIsSet(boolean value) {
    if (!value) {
      this.id_plane = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPlanename() {
    return this.planename;
  }

  public plane setPlanename(@org.apache.thrift.annotation.Nullable java.lang.String planename) {
    this.planename = planename;
    return this;
  }

  public void unsetPlanename() {
    this.planename = null;
  }

  /** Returns true if field planename is set (has been assigned a value) and false otherwise */
  public boolean isSetPlanename() {
    return this.planename != null;
  }

  public void setPlanenameIsSet(boolean value) {
    if (!value) {
      this.planename = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID_PLANE:
      if (value == null) {
        unsetId_plane();
      } else {
        setId_plane((java.lang.String)value);
      }
      break;

    case PLANENAME:
      if (value == null) {
        unsetPlanename();
      } else {
        setPlanename((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID_PLANE:
      return getId_plane();

    case PLANENAME:
      return getPlanename();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID_PLANE:
      return isSetId_plane();
    case PLANENAME:
      return isSetPlanename();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof plane)
      return this.equals((plane)that);
    return false;
  }

  public boolean equals(plane that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id_plane = true && this.isSetId_plane();
    boolean that_present_id_plane = true && that.isSetId_plane();
    if (this_present_id_plane || that_present_id_plane) {
      if (!(this_present_id_plane && that_present_id_plane))
        return false;
      if (!this.id_plane.equals(that.id_plane))
        return false;
    }

    boolean this_present_planename = true && this.isSetPlanename();
    boolean that_present_planename = true && that.isSetPlanename();
    if (this_present_planename || that_present_planename) {
      if (!(this_present_planename && that_present_planename))
        return false;
      if (!this.planename.equals(that.planename))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetId_plane()) ? 131071 : 524287);
    if (isSetId_plane())
      hashCode = hashCode * 8191 + id_plane.hashCode();

    hashCode = hashCode * 8191 + ((isSetPlanename()) ? 131071 : 524287);
    if (isSetPlanename())
      hashCode = hashCode * 8191 + planename.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(plane other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId_plane()).compareTo(other.isSetId_plane());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId_plane()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id_plane, other.id_plane);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPlanename()).compareTo(other.isSetPlanename());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlanename()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.planename, other.planename);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("plane(");
    boolean first = true;

    sb.append("id_plane:");
    if (this.id_plane == null) {
      sb.append("null");
    } else {
      sb.append(this.id_plane);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("planename:");
    if (this.planename == null) {
      sb.append("null");
    } else {
      sb.append(this.planename);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class planeStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public planeStandardScheme getScheme() {
      return new planeStandardScheme();
    }
  }

  private static class planeStandardScheme extends org.apache.thrift.scheme.StandardScheme<plane> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, plane struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID_PLANE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id_plane = iprot.readString();
              struct.setId_planeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PLANENAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.planename = iprot.readString();
              struct.setPlanenameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, plane struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id_plane != null) {
        oprot.writeFieldBegin(ID_PLANE_FIELD_DESC);
        oprot.writeString(struct.id_plane);
        oprot.writeFieldEnd();
      }
      if (struct.planename != null) {
        oprot.writeFieldBegin(PLANENAME_FIELD_DESC);
        oprot.writeString(struct.planename);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class planeTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public planeTupleScheme getScheme() {
      return new planeTupleScheme();
    }
  }

  private static class planeTupleScheme extends org.apache.thrift.scheme.TupleScheme<plane> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, plane struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId_plane()) {
        optionals.set(0);
      }
      if (struct.isSetPlanename()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetId_plane()) {
        oprot.writeString(struct.id_plane);
      }
      if (struct.isSetPlanename()) {
        oprot.writeString(struct.planename);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, plane struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.id_plane = iprot.readString();
        struct.setId_planeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.planename = iprot.readString();
        struct.setPlanenameIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

